services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata  # новый путь
    ports:
      - "5432:5432"
    restart: unless-stopped

  collect_articles:
    image: mariagubina/collect_articles:latest
    depends_on:
      - db
    restart: unless-stopped

  trend_analytics:
    image: mariagubina/trend_analytics:latest
    depends_on:
      - collect_articles
      - db
    restart: unless-stopped

  generate_article:
    image: mariagubina/generate_article:latest
    depends_on:
      - collect_articles
      - trend_analytics
      - db
    restart: unless-stopped

  web_app:
    image: mariagubina/web_app:latest
    ports:
      - "8000:8000"
    depends_on:
      - generate_article
      - db 
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: